[2023-02-04T14:28:32.736+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_lab5_dsa.tarefa_insere_dados manual__2023-02-04T14:28:24.068406+00:00 [queued]>
[2023-02-04T14:28:32.761+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_lab5_dsa.tarefa_insere_dados manual__2023-02-04T14:28:24.068406+00:00 [queued]>
[2023-02-04T14:28:32.761+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T14:28:32.761+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-04T14:28:32.762+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T14:28:32.824+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): tarefa_insere_dados> on 2023-02-04 14:28:24.068406+00:00
[2023-02-04T14:28:32.842+0000] {standard_task_runner.py:55} INFO - Started process 4456 to run task
[2023-02-04T14:28:32.851+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_lab5_dsa', 'tarefa_insere_dados', 'manual__2023-02-04T14:28:24.068406+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpm57emi03']
[2023-02-04T14:28:32.853+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask tarefa_insere_dados
[2023-02-04T14:28:33.096+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_lab5_dsa.tarefa_insere_dados manual__2023-02-04T14:28:24.068406+00:00 [running]> on host 8c271b0bb0d0
[2023-02-04T14:28:33.375+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_lab5_dsa
AIRFLOW_CTX_TASK_ID=tarefa_insere_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T14:28:24.068406+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-04T14:28:24.068406+00:00
[2023-02-04T14:28:33.404+0000] {sql.py:254} INFO - Executing: 
insert into dwdb.tb_funcionarios (id, nome, departamento) values (1000, 'Bob', 'Marketing'), (1001, 'Maria', 'Contabilidade'),(1002, 'Jeremias', 'Engenharia de Dados'), (1003, 'Messi', 'Marketing') ;
[2023-02-04T14:28:33.440+0000] {base.py:73} INFO - Using connection ID 'Postgres' for task execution.
[2023-02-04T14:28:34.305+0000] {base.py:73} INFO - Using connection ID 'Postgres' for task execution.
[2023-02-04T14:28:34.321+0000] {sql.py:375} INFO - Running statement: 
insert into dwdb.tb_funcionarios (id, nome, departamento) values (1000, 'Bob', 'Marketing'), (1001, 'Maria', 'Contabilidade'),(1002, 'Jeremias', 'Engenharia de Dados'), (1003, 'Messi', 'Marketing') ;, parameters: None
[2023-02-04T14:28:34.324+0000] {sql.py:384} INFO - Rows affected: 4
[2023-02-04T14:28:34.341+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=dag_lab5_dsa, task_id=tarefa_insere_dados, execution_date=20230204T142824, start_date=20230204T142832, end_date=20230204T142834
[2023-02-04T14:28:34.399+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-04T14:28:34.461+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
