[2023-02-04T14:30:32.086+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_lab5_dsa.tarefa_insere_dados manual__2023-02-04T14:30:23.794880+00:00 [queued]>
[2023-02-04T14:30:32.128+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_lab5_dsa.tarefa_insere_dados manual__2023-02-04T14:30:23.794880+00:00 [queued]>
[2023-02-04T14:30:32.129+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T14:30:32.129+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-04T14:30:32.129+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T14:30:32.189+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): tarefa_insere_dados> on 2023-02-04 14:30:23.794880+00:00
[2023-02-04T14:30:32.206+0000] {standard_task_runner.py:55} INFO - Started process 4565 to run task
[2023-02-04T14:30:32.218+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_lab5_dsa', 'tarefa_insere_dados', 'manual__2023-02-04T14:30:23.794880+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprexzflql']
[2023-02-04T14:30:32.220+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask tarefa_insere_dados
[2023-02-04T14:30:32.549+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_lab5_dsa.tarefa_insere_dados manual__2023-02-04T14:30:23.794880+00:00 [running]> on host 8c271b0bb0d0
[2023-02-04T14:30:32.787+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_lab5_dsa
AIRFLOW_CTX_TASK_ID=tarefa_insere_dados
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T14:30:23.794880+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-04T14:30:23.794880+00:00
[2023-02-04T14:30:32.790+0000] {sql.py:254} INFO - Executing: 
insert into dwdb.tb_funcionarios (id, nome, departamento) values (1000, 'Bob', 'Marketing'), (1001, 'Maria', 'Contabilidade'),(1002, 'Jeremias', 'Engenharia de Dados'), (1003, 'Messi', 'Marketing') ;
[2023-02-04T14:30:32.811+0000] {base.py:73} INFO - Using connection ID 'Postgres' for task execution.
[2023-02-04T14:30:33.840+0000] {base.py:73} INFO - Using connection ID 'Postgres' for task execution.
[2023-02-04T14:30:33.866+0000] {sql.py:375} INFO - Running statement: 
insert into dwdb.tb_funcionarios (id, nome, departamento) values (1000, 'Bob', 'Marketing'), (1001, 'Maria', 'Contabilidade'),(1002, 'Jeremias', 'Engenharia de Dados'), (1003, 'Messi', 'Marketing') ;, parameters: None
[2023-02-04T14:30:33.868+0000] {sql.py:384} INFO - Rows affected: 4
[2023-02-04T14:30:33.910+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=dag_lab5_dsa, task_id=tarefa_insere_dados, execution_date=20230204T143023, start_date=20230204T143032, end_date=20230204T143033
[2023-02-04T14:30:34.004+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-04T14:30:34.074+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
